name: "Terraform CI/CD"

on:
  push:
    branches:
      - main
  pull_request:

env:
  # GitHub Secrets에서 AWS 자격 증명을 가져옵니다.
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "ap-northeast-2"
  TF_VAR_EC2_PUBLIC_KEY: ${{ secrets.TF_VAR_EC2_PUBLIC_KEY }}

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      # Pull Request가 아닌, main 브랜치에 Push(Merge) 되었을 때만 실제로 리소스를 생성(Apply)합니다.
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false -replace="aws_instance.app_server"
        